"""Execution-agnostic harness for running solver jobs."""

from .config import (
    ConfigError,
    load_all,
    Resource,
    System,
    Solver,
    Job,
    build_jobs_from_solver_specs,
)
from .paths import get_project_root, get_db_path, get_config_dir
from .runner import run_job, run_jobs, RunResult, InvocationControl
from .parser import extract_metrics
from .storage import (
    init_db,
    start_writer,
    stop_writer,
    db_writer_session,
    store_run,
    get_runs,
    get_run_by_id,
    delete_runs,
    get_solver_run_summaries,
    get_all_metrics_series,
    get_metrics_history,
    get_baseline_run,
    set_baseline_run,
    get_baseline_comparison,
    get_job_batch_uuids,
    list_matrix_presets,
    get_matrix_preset,
    upsert_matrix_preset,
    delete_matrix_preset,
    decode_run_row,
)

__all__ = [
    "ConfigError",
    "get_project_root",
    "get_db_path",
    "get_config_dir",
    "load_all",
    "build_jobs_from_solver_specs",
    "Resource",
    "System",
    "Solver",
    "Job",
    "run_job",
    "run_jobs",
    "RunResult",
    "InvocationControl",
    "extract_metrics",
    "init_db",
    "start_writer",
    "stop_writer",
    "db_writer_session",
    "store_run",
    "get_runs",
    "get_run_by_id",
    "delete_runs",
    "get_solver_run_summaries",
    "get_all_metrics_series",
    "get_metrics_history",
    "get_baseline_run",
    "set_baseline_run",
    "get_baseline_comparison",
    "get_job_batch_uuids",
    "list_matrix_presets",
    "get_matrix_preset",
    "upsert_matrix_preset",
    "delete_matrix_preset",
    "decode_run_row",
]
